### Get all
GET http://localhost:3100/api/rockbands

### Get single
GET http://localhost:3100/api/rockbands/1

### Create new
POST http://localhost:3100/api/rockbands
Content-Type: application/json; charset=utf-8

{
    "name": "hejhej",
    "from": "",
    "founded":"a",
    "albums":"a"
}

### Sort
GET http://localhost:3100/api/rockbands?q=ur&sortOrder=desc

### Update
PUT http://localhost:3100/api/rockbands/22
Content-Type: application/json; charset=utf-8

{
    "name": "Kiss",
    "from": "USA",
    "founded": "1973",
    "albums": "20"
}